spring:
  application:
    name: order-service

  # PostgreSQL 설정
#  datasource:
#    url: jdbc:postgresql://localhost:5432/order_db
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 5
#      connection-timeout: 30000

  # JPA 설정
  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true

  # Kafka 설정
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
    consumer:
      group-id: order-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

# 서버 포트
server:
  port: 8081

# 다른 서비스 URL
services:
  inventory:
    url: http://localhost:8082
  payment:
    url: http://localhost:8083

# 로깅
logging:
  level:
    root: INFO
    order: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG